runtime: custom
env: flex

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

network:
  session_affinity: true

manual_scaling:
  instances: 1

entrypoint: streamlit run scripts/evaluate.py --server.port=8080 --server.enableCORS=false