version: '3.9'

services:
  energy-lightgbm-app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: streamlit run scripts/evaluate.py --server.port=8501 --server.enableCORS=false