name: Streamlit App CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 🔄 Checkout repository
      uses: actions/checkout@v3

    - name: 🐍 Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: 📦 Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 🧪 Run training script
      run: python scripts/train.py

    - name: 🐳 Build Docker image
      run: docker build -t energy-lightgbm-app .

    - name: ✅ Test Streamlit run
      run: docker run -d -p 8501:8501 energy-lightgbm-app